FROM openjdk:8

RUN ulimit -n 65536
RUN mkdir -p /opt/zipkin

ADD https://dl.bintray.com/openzipkin/maven/io/zipkin/java/zipkin-server/2.12.5/zipkin-server-2.12.5-exec.jar /opt/zipkin/

WORKDIR /opt/zipkin

ENTRYPOINT ["java", \
    "-jar", \
    "zipkin-server-2.12.5-exec.jar"]
